### ISSUE TITLE
printer not found

### ISSUE THREAD

**Issue by Simone-cogno** [probonopd/ptouch-770#7]
I've tried to run `sudo ptouch-770-write tux-128px-bw.pbm` but I get `Brother PT-H500/P700/E500 printer not found`. I'm using the printer p-touch p700. Do I need to install something? Thanks you in advance!

**Comment by probonopd** [comment]
Are you sure you have switched the printer on? Is is recognized in `lsusb`?

**Comment by Simone-cogno** [comment]
yes it's on and I can see it in the `lsusb`. I will post the result of `lsusb` later but it regognise as `brother Industries, Ltd....` any idea? Do I need to install special drivers maybe?

EDIT: Here the result of `lsusb`:
pi@raspberrypi:~/Desktop/python $ lsusb
```
Bus 001 Device 007: ID 04f9:2064 Brother Industries, Ltd 
Bus 001 Device 005: ID 046d:c52f Logitech, Inc. Unifying Receiver
Bus 001 Device 006: ID 05ac:0250 Apple, Inc. Aluminium Keyboard (ISO)
Bus 001 Device 004: ID 05ac:1006 Apple, Inc. Hub in Aluminum Keyboard
Bus 001 Device 008: ID 054c:0439 Sony Corp. 
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by probonopd** [comment]
This is strange. I did not have to install anything special.

**Comment by Simone-cogno** [comment]
if it has worked for you should also work for me.

I receive also this warning:

`WARNING: Error retrieveing accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus not provided by any .service files`

Any idea about this warning?

**Comment by Simone-cogno** [comment]
any other idea? Or maybe a way to debug or verbose more? I'm a bit stuck because there is no other error message other than "Brother PT-H500/P700/E500 printer not found"

**Comment by probonopd** [comment]
Your USB device ID, 2064, is not one of the supported IDs in this software:

https://github.com/probonopd/ptouch-770/blob/6e2e89883b8719158460c3557ab51c83de851802/ptouch-770-write.c#L537-L540

What exact printer model do you have? Please state all information from the printer's label. Thanks.

We can try adding 2064 and treat it like 2061, and see what happens. I wonder what the difference is. Other country/power supply, maybe?

**Comment by Simone-cogno** [comment]
I've tried to change the USB device ID ptouch-770-write.c from 2061 to 2064 but nothing changed.

The printer is Brother model: PT-P700
Power supply: Adapter CA (AD-E001)

Should be supported right?

**Comment by probonopd** [comment]
Then I don't know... don't have that printer with that USB ID. Don't know how different those printers are.

**Comment by Simone-cogno** [comment]
After I've changed the .c file I've re-run `make`. Is this enough for re-build the program right?

**Comment by probonopd** [comment]
Try

```
make
strip ptouch-770-write
sudo cp ptouch-770-write ptouch-770-gui /usr/local/bin/
sudo ptouch-770-write
```

to be sure you are running the new one.

**Comment by jdpiguet** [comment]
The problem is that the id "2064" indicates that the P700 presents himself as an USB disk.
You need to press the left button "PLite" until it switches off.
After that, the P700 will present himself as a printer, with ID "2061".

**Comment by probonopd** [comment]
Thanks for this hint @jdpiguet
